### ISSUE TITLE
Multiple JSmol cells on single page interact unexpectedly

### ISSUE THREAD

**Issue by paulmasson** [sagemath/sagecell#474] opened 2016-12-25 01:11 UTC
When a single page has multiple embedded cells returning JSmol output, the output for cells above the current evaluation are unexpectedly altered by the current output. This can be seen on this interact page:

https://wiki.sagemath.org/interact/geometry

Evaluate a couple cells with three-dimensional output in order, then scroll up to find that the cells above the last one evaluated have been affected. This does not happen if `show` is replaced by `threejs` in the interacts, so the problem is specific to the JSmol backend for the server.

**Comment by novoselt** [comment] 2016-12-25 01:33
Confirmed... My plan to solve this is: switch threejs handling to the code you have written recently which is distributed with Sage 7.5, then make `show` to use threejs by default. While in my opinion JSmol tends to produce the prettiest pictures, it has a bunch of technical issues that keep coming up. On the other hand, as I recall, threejs also cannot handle too many plots on the same page.

**Comment by paulmasson** [comment] 2016-12-25 01:43
Anything using WebGL, including Three.js, is limited by browsers to a small number of active contexts, typically 16. I already know a way to deal with this dynamically with an external script. Getting it to work with pages containing embedded cells should be as simple as including the script in a tag on the page.

**Comment by novoselt** [comment] 2016-12-25 03:33
Great! I imagine nothing stops me from bundling it with the existing script, so that users don't have to bother with it.

**Comment by novoselt** [comment] 2017-03-31 05:18
Closing this since I don't see much point in working on it - the move to threejs is happening slowly but surely...

**Closed by novoselt** 2017-03-31 05:18 UTC
