### ISSUE TITLE
The cell completely stopped working

### ISSUE THREAD

**Issue by stumpc5** [sagemath/sagecell#454] opened 2015-05-12 09:05 UTC
Here is the output of Firebug:

    TypeError: langOpts[0] is undefined
    langOpts[0].parentNode.value = settings.defaultLanguage;

in line 433 of `embedded_sagecell.js` pulled from `http://sagecell.sagemath.org/static/embedded_sagecell.js`.

**Comment by novoselt** [comment] 2015-05-12 18:16
Can you please provide more details on how to reproduce it and try refreshing the cache? I can't see any problems.

**Comment by stumpc5** [comment] 2015-05-12 18:37
Thanks for looking at my issue!

We have a cell running at `www.findstat.org/StatisticsDatabase/NewStatistic/`, which worked very well and smoothly until recently. Inspecting the loading of the page with Firebug now shows the above error.

Sorry for not thinking about that earlier, but it might also be that some behaviours (or even DOM element namings) have changed, as we read and write the content of the cell to and from other fields, using `$("#sagecell .CodeMirror").get(0).CodeMirror.setValue( [...] )` in lines 438 and 464, 466 of that html page. (This is actually what Jason told us to do in order to access that values).

**Comment by novoselt** [comment] 2015-05-12 22:35
Are you in Europe? May be related to https://groups.google.com/d/topic/sage-support/6d6GyGtDTUE/discussion
When I go to your page and evaluate the cell there, seems to work fine from Canada. (We are using different servers now with a somewhat different configuration.)

**Comment by stumpc5** [comment] 2015-05-13 04:30
Ah, that might be it -- I, and also the people who reported the issue, are all in Europe. Thanks for checking, feel free to close the issue here if you think its not really a sagecell problem.

**Comment by novoselt** [comment] 2015-05-20 21:05
Closing this since it seems that problems are resolved. If not - please let me know!

**Closed by novoselt** 2015-05-20 21:05 UTC
